name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: 'konnyaku256'
          ICON_FIRST: "#243342"
          ICON_SECOND: "#486684"
          BACKGROUND_FIRST: "#34495e"
          BACKGROUND_SECOND: "#34495e"
          LANG: "ja"